[package]
name = "hd2-unit-matching"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Wasm-safe Unit matching logic for HD2 migration"

[dependencies]
hd2-archive-format = { path = "../hd2-archive-format" }
hd2-migrator-data = { path = "../hd2-migrator-data" }
eyre.workspace = true
serde.workspace = true
serde_json.workspace = true
