[package]
name = "hd2_migrator_tauri_ui"
version = "0.1.0"
description = "Tauri desktop UI prototype for hd2-migrator"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "hd2_migrator_tauri_ui_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
hd2-migrator-io = { path = "../../hd2-migrator-io" }
hd2-migrator-core = { path = "../../hd2-migrator-core" }
hd2-migrator-data = { path = "../../hd2-migrator-data" }
svd-core = { path = "../../svd-core" }
eyre.workspace = true
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
pollster.workspace = true
tempfile.workspace = true
walkdir.workspace = true
zip.workspace = true

[target.'cfg(windows)'.dependencies]
winreg = "0.55.0"
